/**
 * Generated by the protoc-gen-ts.  DO NOT EDIT!
 * compiler version: 3.19.4
 * source: common_models.proto
 * git: https://github.com/thesayyn/protoc-gen-ts */
import * as dependency_1 from "./google/protobuf/timestamp";
import * as pb_1 from "google-protobuf";
export declare namespace io.iohk.atala.prism.protos {
    enum SortByDirection {
        SORT_BY_DIRECTION_UNKNOWN = 0,
        SORT_BY_DIRECTION_ASCENDING = 1,
        SORT_BY_DIRECTION_DESCENDING = 2
    }
    enum Ledger {
        UNKNOWN_LEDGER = 0,
        IN_MEMORY = 1,
        CARDANO_TESTNET = 4,
        CARDANO_MAINNET = 5
    }
    enum OperationStatus {
        UNKNOWN_OPERATION = 0,
        PENDING_SUBMISSION = 1,
        AWAIT_CONFIRMATION = 2,
        CONFIRMED_AND_APPLIED = 3,
        CONFIRMED_AND_REJECTED = 4
    }
    class HealthCheckRequest extends pb_1.Message {
        #private;
        constructor(data?: any[] | {});
        static fromObject(data: {}): HealthCheckRequest;
        toObject(): {};
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): HealthCheckRequest;
        serializeBinary(): Uint8Array;
        static deserializeBinary(bytes: Uint8Array): HealthCheckRequest;
    }
    class HealthCheckResponse extends pb_1.Message {
        #private;
        constructor(data?: any[] | {});
        static fromObject(data: {}): HealthCheckResponse;
        toObject(): {};
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): HealthCheckResponse;
        serializeBinary(): Uint8Array;
        static deserializeBinary(bytes: Uint8Array): HealthCheckResponse;
    }
    class Date extends pb_1.Message {
        #private;
        constructor(data?: any[] | {
            year?: number;
            month?: number;
            day?: number;
        });
        get year(): number;
        set year(value: number);
        get month(): number;
        set month(value: number);
        get day(): number;
        set day(value: number);
        static fromObject(data: {
            year?: number;
            month?: number;
            day?: number;
        }): Date;
        toObject(): {
            year?: number | undefined;
            month?: number | undefined;
            day?: number | undefined;
        };
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): Date;
        serializeBinary(): Uint8Array;
        static deserializeBinary(bytes: Uint8Array): Date;
    }
    class TimeInterval extends pb_1.Message {
        #private;
        constructor(data?: any[] | {
            start_timestamp?: dependency_1.google.protobuf.Timestamp;
            end_timestamp?: dependency_1.google.protobuf.Timestamp;
        });
        get start_timestamp(): dependency_1.google.protobuf.Timestamp;
        set start_timestamp(value: dependency_1.google.protobuf.Timestamp);
        get has_start_timestamp(): boolean;
        get end_timestamp(): dependency_1.google.protobuf.Timestamp;
        set end_timestamp(value: dependency_1.google.protobuf.Timestamp);
        get has_end_timestamp(): boolean;
        static fromObject(data: {
            start_timestamp?: ReturnType<typeof dependency_1.google.protobuf.Timestamp.prototype.toObject>;
            end_timestamp?: ReturnType<typeof dependency_1.google.protobuf.Timestamp.prototype.toObject>;
        }): TimeInterval;
        toObject(): {
            start_timestamp?: {
                seconds?: number | undefined;
                nanos?: number | undefined;
            } | undefined;
            end_timestamp?: {
                seconds?: number | undefined;
                nanos?: number | undefined;
            } | undefined;
        };
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): TimeInterval;
        serializeBinary(): Uint8Array;
        static deserializeBinary(bytes: Uint8Array): TimeInterval;
    }
    class BlockInfo extends pb_1.Message {
        #private;
        constructor(data?: any[] | {
            number?: number;
            index?: number;
            timestamp?: dependency_1.google.protobuf.Timestamp;
        });
        get number(): number;
        set number(value: number);
        get index(): number;
        set index(value: number);
        get timestamp(): dependency_1.google.protobuf.Timestamp;
        set timestamp(value: dependency_1.google.protobuf.Timestamp);
        get has_timestamp(): boolean;
        static fromObject(data: {
            number?: number;
            index?: number;
            timestamp?: ReturnType<typeof dependency_1.google.protobuf.Timestamp.prototype.toObject>;
        }): BlockInfo;
        toObject(): {
            number?: number | undefined;
            index?: number | undefined;
            timestamp?: {
                seconds?: number | undefined;
                nanos?: number | undefined;
            } | undefined;
        };
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): BlockInfo;
        serializeBinary(): Uint8Array;
        static deserializeBinary(bytes: Uint8Array): BlockInfo;
    }
    class TransactionInfo extends pb_1.Message {
        #private;
        constructor(data?: any[] | {
            transaction_id?: string;
            ledger?: Ledger;
            block?: BlockInfo;
        });
        get transaction_id(): string;
        set transaction_id(value: string);
        get ledger(): Ledger;
        set ledger(value: Ledger);
        get block(): BlockInfo;
        set block(value: BlockInfo);
        get has_block(): boolean;
        static fromObject(data: {
            transaction_id?: string;
            ledger?: Ledger;
            block?: ReturnType<typeof BlockInfo.prototype.toObject>;
        }): TransactionInfo;
        toObject(): {
            transaction_id?: string | undefined;
            ledger?: Ledger | undefined;
            block?: {
                number?: number | undefined;
                index?: number | undefined;
                timestamp?: {
                    seconds?: number | undefined;
                    nanos?: number | undefined;
                } | undefined;
            } | undefined;
        };
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): TransactionInfo;
        serializeBinary(): Uint8Array;
        static deserializeBinary(bytes: Uint8Array): TransactionInfo;
    }
}
