/**
 * Generated by the protoc-gen-ts.  DO NOT EDIT!
 * compiler version: 3.19.4
 * source: node_models.proto
 * git: https://github.com/thesayyn/protoc-gen-ts */
import * as dependency_1 from "./common_models";
import * as dependency_2 from "./google/protobuf/timestamp";
import * as pb_1 from "google-protobuf";
export declare namespace io.iohk.atala.prism.protos {
    enum KeyUsage {
        UNKNOWN_KEY = 0,
        MASTER_KEY = 1,
        ISSUING_KEY = 2,
        KEY_AGREEMENT_KEY = 3,
        AUTHENTICATION_KEY = 4,
        REVOCATION_KEY = 5,
        CAPABILITY_INVOCATION_KEY = 6,
        CAPABILITY_DELEGATION_KEY = 7
    }
    class TimestampInfo extends pb_1.Message {
        #private;
        constructor(data?: any[] | {
            block_sequence_number?: number;
            operation_sequence_number?: number;
            block_timestamp?: dependency_2.google.protobuf.Timestamp;
        });
        get block_sequence_number(): number;
        set block_sequence_number(value: number);
        get operation_sequence_number(): number;
        set operation_sequence_number(value: number);
        get block_timestamp(): dependency_2.google.protobuf.Timestamp;
        set block_timestamp(value: dependency_2.google.protobuf.Timestamp);
        get has_block_timestamp(): boolean;
        static fromObject(data: {
            block_sequence_number?: number;
            operation_sequence_number?: number;
            block_timestamp?: ReturnType<typeof dependency_2.google.protobuf.Timestamp.prototype.toObject>;
        }): TimestampInfo;
        toObject(): {
            block_sequence_number?: number | undefined;
            operation_sequence_number?: number | undefined;
            block_timestamp?: {
                seconds?: number | undefined;
                nanos?: number | undefined;
            } | undefined;
        };
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): TimestampInfo;
        serializeBinary(): Uint8Array;
        static deserializeBinary(bytes: Uint8Array): TimestampInfo;
    }
    class ECKeyData extends pb_1.Message {
        #private;
        constructor(data?: any[] | {
            curve?: string;
            x?: Uint8Array;
            y?: Uint8Array;
        });
        get curve(): string;
        set curve(value: string);
        get x(): Uint8Array;
        set x(value: Uint8Array);
        get y(): Uint8Array;
        set y(value: Uint8Array);
        static fromObject(data: {
            curve?: string;
            x?: Uint8Array;
            y?: Uint8Array;
        }): ECKeyData;
        toObject(): {
            curve?: string | undefined;
            x?: Uint8Array | undefined;
            y?: Uint8Array | undefined;
        };
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): ECKeyData;
        serializeBinary(): Uint8Array;
        static deserializeBinary(bytes: Uint8Array): ECKeyData;
    }
    class CompressedECKeyData extends pb_1.Message {
        #private;
        constructor(data?: any[] | {
            curve?: string;
            data?: Uint8Array;
        });
        get curve(): string;
        set curve(value: string);
        get data(): Uint8Array;
        set data(value: Uint8Array);
        static fromObject(data: {
            curve?: string;
            data?: Uint8Array;
        }): CompressedECKeyData;
        toObject(): {
            curve?: string | undefined;
            data?: Uint8Array | undefined;
        };
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): CompressedECKeyData;
        serializeBinary(): Uint8Array;
        static deserializeBinary(bytes: Uint8Array): CompressedECKeyData;
    }
    class PublicKey extends pb_1.Message {
        #private;
        constructor(data?: any[] | ({
            id?: string;
            usage?: KeyUsage;
            added_on?: LedgerData;
            revoked_on?: LedgerData;
        } & (({
            ec_key_data?: ECKeyData;
            compressed_ec_key_data?: never;
        } | {
            ec_key_data?: never;
            compressed_ec_key_data?: CompressedECKeyData;
        }))));
        get id(): string;
        set id(value: string);
        get usage(): KeyUsage;
        set usage(value: KeyUsage);
        get added_on(): LedgerData;
        set added_on(value: LedgerData);
        get has_added_on(): boolean;
        get revoked_on(): LedgerData;
        set revoked_on(value: LedgerData);
        get has_revoked_on(): boolean;
        get ec_key_data(): ECKeyData;
        set ec_key_data(value: ECKeyData);
        get has_ec_key_data(): boolean;
        get compressed_ec_key_data(): CompressedECKeyData;
        set compressed_ec_key_data(value: CompressedECKeyData);
        get has_compressed_ec_key_data(): boolean;
        get key_data(): "none" | "ec_key_data" | "compressed_ec_key_data";
        static fromObject(data: {
            id?: string;
            usage?: KeyUsage;
            added_on?: ReturnType<typeof LedgerData.prototype.toObject>;
            revoked_on?: ReturnType<typeof LedgerData.prototype.toObject>;
            ec_key_data?: ReturnType<typeof ECKeyData.prototype.toObject>;
            compressed_ec_key_data?: ReturnType<typeof CompressedECKeyData.prototype.toObject>;
        }): PublicKey;
        toObject(): {
            id?: string | undefined;
            usage?: KeyUsage | undefined;
            added_on?: {
                transaction_id?: string | undefined;
                ledger?: dependency_1.io.iohk.atala.prism.protos.Ledger | undefined;
                timestamp_info?: {
                    block_sequence_number?: number | undefined;
                    operation_sequence_number?: number | undefined;
                    block_timestamp?: {
                        seconds?: number | undefined;
                        nanos?: number | undefined;
                    } | undefined;
                } | undefined;
            } | undefined;
            revoked_on?: {
                transaction_id?: string | undefined;
                ledger?: dependency_1.io.iohk.atala.prism.protos.Ledger | undefined;
                timestamp_info?: {
                    block_sequence_number?: number | undefined;
                    operation_sequence_number?: number | undefined;
                    block_timestamp?: {
                        seconds?: number | undefined;
                        nanos?: number | undefined;
                    } | undefined;
                } | undefined;
            } | undefined;
            ec_key_data?: {
                curve?: string | undefined;
                x?: Uint8Array | undefined;
                y?: Uint8Array | undefined;
            } | undefined;
            compressed_ec_key_data?: {
                curve?: string | undefined;
                data?: Uint8Array | undefined;
            } | undefined;
        };
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): PublicKey;
        serializeBinary(): Uint8Array;
        static deserializeBinary(bytes: Uint8Array): PublicKey;
    }
    class DIDData extends pb_1.Message {
        #private;
        constructor(data?: any[] | {
            id?: string;
            public_keys?: PublicKey[];
            services?: Service[];
        });
        get id(): string;
        set id(value: string);
        get public_keys(): PublicKey[];
        set public_keys(value: PublicKey[]);
        get services(): Service[];
        set services(value: Service[]);
        static fromObject(data: {
            id?: string;
            public_keys?: ReturnType<typeof PublicKey.prototype.toObject>[];
            services?: ReturnType<typeof Service.prototype.toObject>[];
        }): DIDData;
        toObject(): {
            id?: string | undefined;
            public_keys?: {
                id?: string | undefined;
                usage?: KeyUsage | undefined;
                added_on?: {
                    transaction_id?: string | undefined;
                    ledger?: dependency_1.io.iohk.atala.prism.protos.Ledger | undefined;
                    timestamp_info?: {
                        block_sequence_number?: number | undefined;
                        operation_sequence_number?: number | undefined;
                        block_timestamp?: {
                            seconds?: number | undefined;
                            nanos?: number | undefined;
                        } | undefined;
                    } | undefined;
                } | undefined;
                revoked_on?: {
                    transaction_id?: string | undefined;
                    ledger?: dependency_1.io.iohk.atala.prism.protos.Ledger | undefined;
                    timestamp_info?: {
                        block_sequence_number?: number | undefined;
                        operation_sequence_number?: number | undefined;
                        block_timestamp?: {
                            seconds?: number | undefined;
                            nanos?: number | undefined;
                        } | undefined;
                    } | undefined;
                } | undefined;
                ec_key_data?: {
                    curve?: string | undefined;
                    x?: Uint8Array | undefined;
                    y?: Uint8Array | undefined;
                } | undefined;
                compressed_ec_key_data?: {
                    curve?: string | undefined;
                    data?: Uint8Array | undefined;
                } | undefined;
            }[] | undefined;
            services?: {
                id?: string | undefined;
                type?: string | undefined;
                service_endpoint?: string[] | undefined;
                added_on?: {
                    transaction_id?: string | undefined;
                    ledger?: dependency_1.io.iohk.atala.prism.protos.Ledger | undefined;
                    timestamp_info?: {
                        block_sequence_number?: number | undefined;
                        operation_sequence_number?: number | undefined;
                        block_timestamp?: {
                            seconds?: number | undefined;
                            nanos?: number | undefined;
                        } | undefined;
                    } | undefined;
                } | undefined;
                deleted_on?: {
                    transaction_id?: string | undefined;
                    ledger?: dependency_1.io.iohk.atala.prism.protos.Ledger | undefined;
                    timestamp_info?: {
                        block_sequence_number?: number | undefined;
                        operation_sequence_number?: number | undefined;
                        block_timestamp?: {
                            seconds?: number | undefined;
                            nanos?: number | undefined;
                        } | undefined;
                    } | undefined;
                } | undefined;
            }[] | undefined;
        };
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): DIDData;
        serializeBinary(): Uint8Array;
        static deserializeBinary(bytes: Uint8Array): DIDData;
    }
    class CreateDIDOperation extends pb_1.Message {
        #private;
        constructor(data?: any[] | {
            did_data?: CreateDIDOperation.DIDCreationData;
        });
        get did_data(): CreateDIDOperation.DIDCreationData;
        set did_data(value: CreateDIDOperation.DIDCreationData);
        get has_did_data(): boolean;
        static fromObject(data: {
            did_data?: ReturnType<typeof CreateDIDOperation.DIDCreationData.prototype.toObject>;
        }): CreateDIDOperation;
        toObject(): {
            did_data?: {
                public_keys?: {
                    id?: string | undefined;
                    usage?: KeyUsage | undefined;
                    added_on?: {
                        transaction_id?: string | undefined;
                        ledger?: dependency_1.io.iohk.atala.prism.protos.Ledger | undefined;
                        timestamp_info?: {
                            block_sequence_number?: number | undefined;
                            operation_sequence_number?: number | undefined;
                            block_timestamp?: {
                                seconds?: number | undefined;
                                nanos?: number | undefined;
                            } | undefined;
                        } | undefined;
                    } | undefined;
                    revoked_on?: {
                        transaction_id?: string | undefined;
                        ledger?: dependency_1.io.iohk.atala.prism.protos.Ledger | undefined;
                        timestamp_info?: {
                            block_sequence_number?: number | undefined;
                            operation_sequence_number?: number | undefined;
                            block_timestamp?: {
                                seconds?: number | undefined;
                                nanos?: number | undefined;
                            } | undefined;
                        } | undefined;
                    } | undefined;
                    ec_key_data?: {
                        curve?: string | undefined;
                        x?: Uint8Array | undefined;
                        y?: Uint8Array | undefined;
                    } | undefined;
                    compressed_ec_key_data?: {
                        curve?: string | undefined;
                        data?: Uint8Array | undefined;
                    } | undefined;
                }[] | undefined;
                services?: {
                    id?: string | undefined;
                    type?: string | undefined;
                    service_endpoint?: string[] | undefined;
                    added_on?: {
                        transaction_id?: string | undefined;
                        ledger?: dependency_1.io.iohk.atala.prism.protos.Ledger | undefined;
                        timestamp_info?: {
                            block_sequence_number?: number | undefined;
                            operation_sequence_number?: number | undefined;
                            block_timestamp?: {
                                seconds?: number | undefined;
                                nanos?: number | undefined;
                            } | undefined;
                        } | undefined;
                    } | undefined;
                    deleted_on?: {
                        transaction_id?: string | undefined;
                        ledger?: dependency_1.io.iohk.atala.prism.protos.Ledger | undefined;
                        timestamp_info?: {
                            block_sequence_number?: number | undefined;
                            operation_sequence_number?: number | undefined;
                            block_timestamp?: {
                                seconds?: number | undefined;
                                nanos?: number | undefined;
                            } | undefined;
                        } | undefined;
                    } | undefined;
                }[] | undefined;
            } | undefined;
        };
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): CreateDIDOperation;
        serializeBinary(): Uint8Array;
        static deserializeBinary(bytes: Uint8Array): CreateDIDOperation;
    }
    namespace CreateDIDOperation {
        class DIDCreationData extends pb_1.Message {
            #private;
            constructor(data?: any[] | {
                public_keys?: PublicKey[];
                services?: Service[];
            });
            get public_keys(): PublicKey[];
            set public_keys(value: PublicKey[]);
            get services(): Service[];
            set services(value: Service[]);
            static fromObject(data: {
                public_keys?: ReturnType<typeof PublicKey.prototype.toObject>[];
                services?: ReturnType<typeof Service.prototype.toObject>[];
            }): DIDCreationData;
            toObject(): {
                public_keys?: {
                    id?: string | undefined;
                    usage?: KeyUsage | undefined;
                    added_on?: {
                        transaction_id?: string | undefined;
                        ledger?: dependency_1.io.iohk.atala.prism.protos.Ledger | undefined;
                        timestamp_info?: {
                            block_sequence_number?: number | undefined;
                            operation_sequence_number?: number | undefined;
                            block_timestamp?: {
                                seconds?: number | undefined;
                                nanos?: number | undefined;
                            } | undefined;
                        } | undefined;
                    } | undefined;
                    revoked_on?: {
                        transaction_id?: string | undefined;
                        ledger?: dependency_1.io.iohk.atala.prism.protos.Ledger | undefined;
                        timestamp_info?: {
                            block_sequence_number?: number | undefined;
                            operation_sequence_number?: number | undefined;
                            block_timestamp?: {
                                seconds?: number | undefined;
                                nanos?: number | undefined;
                            } | undefined;
                        } | undefined;
                    } | undefined;
                    ec_key_data?: {
                        curve?: string | undefined;
                        x?: Uint8Array | undefined;
                        y?: Uint8Array | undefined;
                    } | undefined;
                    compressed_ec_key_data?: {
                        curve?: string | undefined;
                        data?: Uint8Array | undefined;
                    } | undefined;
                }[] | undefined;
                services?: {
                    id?: string | undefined;
                    type?: string | undefined;
                    service_endpoint?: string[] | undefined;
                    added_on?: {
                        transaction_id?: string | undefined;
                        ledger?: dependency_1.io.iohk.atala.prism.protos.Ledger | undefined;
                        timestamp_info?: {
                            block_sequence_number?: number | undefined;
                            operation_sequence_number?: number | undefined;
                            block_timestamp?: {
                                seconds?: number | undefined;
                                nanos?: number | undefined;
                            } | undefined;
                        } | undefined;
                    } | undefined;
                    deleted_on?: {
                        transaction_id?: string | undefined;
                        ledger?: dependency_1.io.iohk.atala.prism.protos.Ledger | undefined;
                        timestamp_info?: {
                            block_sequence_number?: number | undefined;
                            operation_sequence_number?: number | undefined;
                            block_timestamp?: {
                                seconds?: number | undefined;
                                nanos?: number | undefined;
                            } | undefined;
                        } | undefined;
                    } | undefined;
                }[] | undefined;
            };
            serialize(): Uint8Array;
            serialize(w: pb_1.BinaryWriter): void;
            static deserialize(bytes: Uint8Array | pb_1.BinaryReader): DIDCreationData;
            serializeBinary(): Uint8Array;
            static deserializeBinary(bytes: Uint8Array): DIDCreationData;
        }
    }
    class AddKeyAction extends pb_1.Message {
        #private;
        constructor(data?: any[] | {
            key?: PublicKey;
        });
        get key(): PublicKey;
        set key(value: PublicKey);
        get has_key(): boolean;
        static fromObject(data: {
            key?: ReturnType<typeof PublicKey.prototype.toObject>;
        }): AddKeyAction;
        toObject(): {
            key?: {
                id?: string | undefined;
                usage?: KeyUsage | undefined;
                added_on?: {
                    transaction_id?: string | undefined;
                    ledger?: dependency_1.io.iohk.atala.prism.protos.Ledger | undefined;
                    timestamp_info?: {
                        block_sequence_number?: number | undefined;
                        operation_sequence_number?: number | undefined;
                        block_timestamp?: {
                            seconds?: number | undefined;
                            nanos?: number | undefined;
                        } | undefined;
                    } | undefined;
                } | undefined;
                revoked_on?: {
                    transaction_id?: string | undefined;
                    ledger?: dependency_1.io.iohk.atala.prism.protos.Ledger | undefined;
                    timestamp_info?: {
                        block_sequence_number?: number | undefined;
                        operation_sequence_number?: number | undefined;
                        block_timestamp?: {
                            seconds?: number | undefined;
                            nanos?: number | undefined;
                        } | undefined;
                    } | undefined;
                } | undefined;
                ec_key_data?: {
                    curve?: string | undefined;
                    x?: Uint8Array | undefined;
                    y?: Uint8Array | undefined;
                } | undefined;
                compressed_ec_key_data?: {
                    curve?: string | undefined;
                    data?: Uint8Array | undefined;
                } | undefined;
            } | undefined;
        };
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): AddKeyAction;
        serializeBinary(): Uint8Array;
        static deserializeBinary(bytes: Uint8Array): AddKeyAction;
    }
    class RemoveKeyAction extends pb_1.Message {
        #private;
        constructor(data?: any[] | {
            keyId?: string;
        });
        get keyId(): string;
        set keyId(value: string);
        static fromObject(data: {
            keyId?: string;
        }): RemoveKeyAction;
        toObject(): {
            keyId?: string | undefined;
        };
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): RemoveKeyAction;
        serializeBinary(): Uint8Array;
        static deserializeBinary(bytes: Uint8Array): RemoveKeyAction;
    }
    class AddServiceAction extends pb_1.Message {
        #private;
        constructor(data?: any[] | {
            service?: Service;
        });
        get service(): Service;
        set service(value: Service);
        get has_service(): boolean;
        static fromObject(data: {
            service?: ReturnType<typeof Service.prototype.toObject>;
        }): AddServiceAction;
        toObject(): {
            service?: {
                id?: string | undefined;
                type?: string | undefined;
                service_endpoint?: string[] | undefined;
                added_on?: {
                    transaction_id?: string | undefined;
                    ledger?: dependency_1.io.iohk.atala.prism.protos.Ledger | undefined;
                    timestamp_info?: {
                        block_sequence_number?: number | undefined;
                        operation_sequence_number?: number | undefined;
                        block_timestamp?: {
                            seconds?: number | undefined;
                            nanos?: number | undefined;
                        } | undefined;
                    } | undefined;
                } | undefined;
                deleted_on?: {
                    transaction_id?: string | undefined;
                    ledger?: dependency_1.io.iohk.atala.prism.protos.Ledger | undefined;
                    timestamp_info?: {
                        block_sequence_number?: number | undefined;
                        operation_sequence_number?: number | undefined;
                        block_timestamp?: {
                            seconds?: number | undefined;
                            nanos?: number | undefined;
                        } | undefined;
                    } | undefined;
                } | undefined;
            } | undefined;
        };
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): AddServiceAction;
        serializeBinary(): Uint8Array;
        static deserializeBinary(bytes: Uint8Array): AddServiceAction;
    }
    class RemoveServiceAction extends pb_1.Message {
        #private;
        constructor(data?: any[] | {
            serviceId?: string;
        });
        get serviceId(): string;
        set serviceId(value: string);
        static fromObject(data: {
            serviceId?: string;
        }): RemoveServiceAction;
        toObject(): {
            serviceId?: string | undefined;
        };
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): RemoveServiceAction;
        serializeBinary(): Uint8Array;
        static deserializeBinary(bytes: Uint8Array): RemoveServiceAction;
    }
    class UpdateServiceAction extends pb_1.Message {
        #private;
        constructor(data?: any[] | {
            serviceId?: string;
            type?: string;
            service_endpoints?: string[];
        });
        get serviceId(): string;
        set serviceId(value: string);
        get type(): string;
        set type(value: string);
        get service_endpoints(): string[];
        set service_endpoints(value: string[]);
        static fromObject(data: {
            serviceId?: string;
            type?: string;
            service_endpoints?: string[];
        }): UpdateServiceAction;
        toObject(): {
            serviceId?: string | undefined;
            type?: string | undefined;
            service_endpoints?: string[] | undefined;
        };
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): UpdateServiceAction;
        serializeBinary(): Uint8Array;
        static deserializeBinary(bytes: Uint8Array): UpdateServiceAction;
    }
    class UpdateDIDAction extends pb_1.Message {
        #private;
        constructor(data?: any[] | ({} & (({
            add_key?: AddKeyAction;
            remove_key?: never;
            add_service?: never;
            remove_service?: never;
            update_service?: never;
        } | {
            add_key?: never;
            remove_key?: RemoveKeyAction;
            add_service?: never;
            remove_service?: never;
            update_service?: never;
        } | {
            add_key?: never;
            remove_key?: never;
            add_service?: AddServiceAction;
            remove_service?: never;
            update_service?: never;
        } | {
            add_key?: never;
            remove_key?: never;
            add_service?: never;
            remove_service?: RemoveServiceAction;
            update_service?: never;
        } | {
            add_key?: never;
            remove_key?: never;
            add_service?: never;
            remove_service?: never;
            update_service?: UpdateServiceAction;
        }))));
        get add_key(): AddKeyAction;
        set add_key(value: AddKeyAction);
        get has_add_key(): boolean;
        get remove_key(): RemoveKeyAction;
        set remove_key(value: RemoveKeyAction);
        get has_remove_key(): boolean;
        get add_service(): AddServiceAction;
        set add_service(value: AddServiceAction);
        get has_add_service(): boolean;
        get remove_service(): RemoveServiceAction;
        set remove_service(value: RemoveServiceAction);
        get has_remove_service(): boolean;
        get update_service(): UpdateServiceAction;
        set update_service(value: UpdateServiceAction);
        get has_update_service(): boolean;
        get action(): "none" | "add_key" | "remove_key" | "add_service" | "remove_service" | "update_service";
        static fromObject(data: {
            add_key?: ReturnType<typeof AddKeyAction.prototype.toObject>;
            remove_key?: ReturnType<typeof RemoveKeyAction.prototype.toObject>;
            add_service?: ReturnType<typeof AddServiceAction.prototype.toObject>;
            remove_service?: ReturnType<typeof RemoveServiceAction.prototype.toObject>;
            update_service?: ReturnType<typeof UpdateServiceAction.prototype.toObject>;
        }): UpdateDIDAction;
        toObject(): {
            add_key?: {
                key?: {
                    id?: string | undefined;
                    usage?: KeyUsage | undefined;
                    added_on?: {
                        transaction_id?: string | undefined;
                        ledger?: dependency_1.io.iohk.atala.prism.protos.Ledger | undefined;
                        timestamp_info?: {
                            block_sequence_number?: number | undefined;
                            operation_sequence_number?: number | undefined;
                            block_timestamp?: {
                                seconds?: number | undefined;
                                nanos?: number | undefined;
                            } | undefined;
                        } | undefined;
                    } | undefined;
                    revoked_on?: {
                        transaction_id?: string | undefined;
                        ledger?: dependency_1.io.iohk.atala.prism.protos.Ledger | undefined;
                        timestamp_info?: {
                            block_sequence_number?: number | undefined;
                            operation_sequence_number?: number | undefined;
                            block_timestamp?: {
                                seconds?: number | undefined;
                                nanos?: number | undefined;
                            } | undefined;
                        } | undefined;
                    } | undefined;
                    ec_key_data?: {
                        curve?: string | undefined;
                        x?: Uint8Array | undefined;
                        y?: Uint8Array | undefined;
                    } | undefined;
                    compressed_ec_key_data?: {
                        curve?: string | undefined;
                        data?: Uint8Array | undefined;
                    } | undefined;
                } | undefined;
            } | undefined;
            remove_key?: {
                keyId?: string | undefined;
            } | undefined;
            add_service?: {
                service?: {
                    id?: string | undefined;
                    type?: string | undefined;
                    service_endpoint?: string[] | undefined;
                    added_on?: {
                        transaction_id?: string | undefined;
                        ledger?: dependency_1.io.iohk.atala.prism.protos.Ledger | undefined;
                        timestamp_info?: {
                            block_sequence_number?: number | undefined;
                            operation_sequence_number?: number | undefined;
                            block_timestamp?: {
                                seconds?: number | undefined;
                                nanos?: number | undefined;
                            } | undefined;
                        } | undefined;
                    } | undefined;
                    deleted_on?: {
                        transaction_id?: string | undefined;
                        ledger?: dependency_1.io.iohk.atala.prism.protos.Ledger | undefined;
                        timestamp_info?: {
                            block_sequence_number?: number | undefined;
                            operation_sequence_number?: number | undefined;
                            block_timestamp?: {
                                seconds?: number | undefined;
                                nanos?: number | undefined;
                            } | undefined;
                        } | undefined;
                    } | undefined;
                } | undefined;
            } | undefined;
            remove_service?: {
                serviceId?: string | undefined;
            } | undefined;
            update_service?: {
                serviceId?: string | undefined;
                type?: string | undefined;
                service_endpoints?: string[] | undefined;
            } | undefined;
        };
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): UpdateDIDAction;
        serializeBinary(): Uint8Array;
        static deserializeBinary(bytes: Uint8Array): UpdateDIDAction;
    }
    class UpdateDIDOperation extends pb_1.Message {
        #private;
        constructor(data?: any[] | {
            previous_operation_hash?: Uint8Array;
            id?: string;
            actions?: UpdateDIDAction[];
        });
        get previous_operation_hash(): Uint8Array;
        set previous_operation_hash(value: Uint8Array);
        get id(): string;
        set id(value: string);
        get actions(): UpdateDIDAction[];
        set actions(value: UpdateDIDAction[]);
        static fromObject(data: {
            previous_operation_hash?: Uint8Array;
            id?: string;
            actions?: ReturnType<typeof UpdateDIDAction.prototype.toObject>[];
        }): UpdateDIDOperation;
        toObject(): {
            previous_operation_hash?: Uint8Array | undefined;
            id?: string | undefined;
            actions?: {
                add_key?: {
                    key?: {
                        id?: string | undefined;
                        usage?: KeyUsage | undefined;
                        added_on?: {
                            transaction_id?: string | undefined;
                            ledger?: dependency_1.io.iohk.atala.prism.protos.Ledger | undefined;
                            timestamp_info?: {
                                block_sequence_number?: number | undefined;
                                operation_sequence_number?: number | undefined;
                                block_timestamp?: {
                                    seconds?: number | undefined;
                                    nanos?: number | undefined;
                                } | undefined;
                            } | undefined;
                        } | undefined;
                        revoked_on?: {
                            transaction_id?: string | undefined;
                            ledger?: dependency_1.io.iohk.atala.prism.protos.Ledger | undefined;
                            timestamp_info?: {
                                block_sequence_number?: number | undefined;
                                operation_sequence_number?: number | undefined;
                                block_timestamp?: {
                                    seconds?: number | undefined;
                                    nanos?: number | undefined;
                                } | undefined;
                            } | undefined;
                        } | undefined;
                        ec_key_data?: {
                            curve?: string | undefined;
                            x?: Uint8Array | undefined;
                            y?: Uint8Array | undefined;
                        } | undefined;
                        compressed_ec_key_data?: {
                            curve?: string | undefined;
                            data?: Uint8Array | undefined;
                        } | undefined;
                    } | undefined;
                } | undefined;
                remove_key?: {
                    keyId?: string | undefined;
                } | undefined;
                add_service?: {
                    service?: {
                        id?: string | undefined;
                        type?: string | undefined;
                        service_endpoint?: string[] | undefined;
                        added_on?: {
                            transaction_id?: string | undefined;
                            ledger?: dependency_1.io.iohk.atala.prism.protos.Ledger | undefined;
                            timestamp_info?: {
                                block_sequence_number?: number | undefined;
                                operation_sequence_number?: number | undefined;
                                block_timestamp?: {
                                    seconds?: number | undefined;
                                    nanos?: number | undefined;
                                } | undefined;
                            } | undefined;
                        } | undefined;
                        deleted_on?: {
                            transaction_id?: string | undefined;
                            ledger?: dependency_1.io.iohk.atala.prism.protos.Ledger | undefined;
                            timestamp_info?: {
                                block_sequence_number?: number | undefined;
                                operation_sequence_number?: number | undefined;
                                block_timestamp?: {
                                    seconds?: number | undefined;
                                    nanos?: number | undefined;
                                } | undefined;
                            } | undefined;
                        } | undefined;
                    } | undefined;
                } | undefined;
                remove_service?: {
                    serviceId?: string | undefined;
                } | undefined;
                update_service?: {
                    serviceId?: string | undefined;
                    type?: string | undefined;
                    service_endpoints?: string[] | undefined;
                } | undefined;
            }[] | undefined;
        };
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): UpdateDIDOperation;
        serializeBinary(): Uint8Array;
        static deserializeBinary(bytes: Uint8Array): UpdateDIDOperation;
    }
    class CredentialBatchData extends pb_1.Message {
        #private;
        constructor(data?: any[] | {
            issuer_did?: string;
            merkle_root?: Uint8Array;
        });
        get issuer_did(): string;
        set issuer_did(value: string);
        get merkle_root(): Uint8Array;
        set merkle_root(value: Uint8Array);
        static fromObject(data: {
            issuer_did?: string;
            merkle_root?: Uint8Array;
        }): CredentialBatchData;
        toObject(): {
            issuer_did?: string | undefined;
            merkle_root?: Uint8Array | undefined;
        };
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): CredentialBatchData;
        serializeBinary(): Uint8Array;
        static deserializeBinary(bytes: Uint8Array): CredentialBatchData;
    }
    class IssueCredentialBatchOperation extends pb_1.Message {
        #private;
        constructor(data?: any[] | {
            credential_batch_data?: CredentialBatchData;
        });
        get credential_batch_data(): CredentialBatchData;
        set credential_batch_data(value: CredentialBatchData);
        get has_credential_batch_data(): boolean;
        static fromObject(data: {
            credential_batch_data?: ReturnType<typeof CredentialBatchData.prototype.toObject>;
        }): IssueCredentialBatchOperation;
        toObject(): {
            credential_batch_data?: {
                issuer_did?: string | undefined;
                merkle_root?: Uint8Array | undefined;
            } | undefined;
        };
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): IssueCredentialBatchOperation;
        serializeBinary(): Uint8Array;
        static deserializeBinary(bytes: Uint8Array): IssueCredentialBatchOperation;
    }
    class RevokeCredentialsOperation extends pb_1.Message {
        #private;
        constructor(data?: any[] | {
            previous_operation_hash?: Uint8Array;
            credential_batch_id?: string;
            credentials_to_revoke?: Uint8Array[];
        });
        get previous_operation_hash(): Uint8Array;
        set previous_operation_hash(value: Uint8Array);
        get credential_batch_id(): string;
        set credential_batch_id(value: string);
        get credentials_to_revoke(): Uint8Array[];
        set credentials_to_revoke(value: Uint8Array[]);
        static fromObject(data: {
            previous_operation_hash?: Uint8Array;
            credential_batch_id?: string;
            credentials_to_revoke?: Uint8Array[];
        }): RevokeCredentialsOperation;
        toObject(): {
            previous_operation_hash?: Uint8Array | undefined;
            credential_batch_id?: string | undefined;
            credentials_to_revoke?: Uint8Array[] | undefined;
        };
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): RevokeCredentialsOperation;
        serializeBinary(): Uint8Array;
        static deserializeBinary(bytes: Uint8Array): RevokeCredentialsOperation;
    }
    class ProtocolVersionUpdateOperation extends pb_1.Message {
        #private;
        constructor(data?: any[] | {
            proposer_did?: string;
            version?: ProtocolVersionInfo;
        });
        get proposer_did(): string;
        set proposer_did(value: string);
        get version(): ProtocolVersionInfo;
        set version(value: ProtocolVersionInfo);
        get has_version(): boolean;
        static fromObject(data: {
            proposer_did?: string;
            version?: ReturnType<typeof ProtocolVersionInfo.prototype.toObject>;
        }): ProtocolVersionUpdateOperation;
        toObject(): {
            proposer_did?: string | undefined;
            version?: {
                version_name?: string | undefined;
                effective_since?: number | undefined;
                protocol_version?: {
                    major_version?: number | undefined;
                    minor_version?: number | undefined;
                } | undefined;
            } | undefined;
        };
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): ProtocolVersionUpdateOperation;
        serializeBinary(): Uint8Array;
        static deserializeBinary(bytes: Uint8Array): ProtocolVersionUpdateOperation;
    }
    class ProtocolVersion extends pb_1.Message {
        #private;
        constructor(data?: any[] | {
            major_version?: number;
            minor_version?: number;
        });
        get major_version(): number;
        set major_version(value: number);
        get minor_version(): number;
        set minor_version(value: number);
        static fromObject(data: {
            major_version?: number;
            minor_version?: number;
        }): ProtocolVersion;
        toObject(): {
            major_version?: number | undefined;
            minor_version?: number | undefined;
        };
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): ProtocolVersion;
        serializeBinary(): Uint8Array;
        static deserializeBinary(bytes: Uint8Array): ProtocolVersion;
    }
    class ProtocolVersionInfo extends pb_1.Message {
        #private;
        constructor(data?: any[] | {
            version_name?: string;
            effective_since?: number;
            protocol_version?: ProtocolVersion;
        });
        get version_name(): string;
        set version_name(value: string);
        get effective_since(): number;
        set effective_since(value: number);
        get protocol_version(): ProtocolVersion;
        set protocol_version(value: ProtocolVersion);
        get has_protocol_version(): boolean;
        static fromObject(data: {
            version_name?: string;
            effective_since?: number;
            protocol_version?: ReturnType<typeof ProtocolVersion.prototype.toObject>;
        }): ProtocolVersionInfo;
        toObject(): {
            version_name?: string | undefined;
            effective_since?: number | undefined;
            protocol_version?: {
                major_version?: number | undefined;
                minor_version?: number | undefined;
            } | undefined;
        };
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): ProtocolVersionInfo;
        serializeBinary(): Uint8Array;
        static deserializeBinary(bytes: Uint8Array): ProtocolVersionInfo;
    }
    class DeactivateDIDOperation extends pb_1.Message {
        #private;
        constructor(data?: any[] | {
            previous_operation_hash?: Uint8Array;
            id?: string;
        });
        get previous_operation_hash(): Uint8Array;
        set previous_operation_hash(value: Uint8Array);
        get id(): string;
        set id(value: string);
        static fromObject(data: {
            previous_operation_hash?: Uint8Array;
            id?: string;
        }): DeactivateDIDOperation;
        toObject(): {
            previous_operation_hash?: Uint8Array | undefined;
            id?: string | undefined;
        };
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): DeactivateDIDOperation;
        serializeBinary(): Uint8Array;
        static deserializeBinary(bytes: Uint8Array): DeactivateDIDOperation;
    }
    class AtalaOperation extends pb_1.Message {
        #private;
        constructor(data?: any[] | ({} & (({
            create_did?: CreateDIDOperation;
            update_did?: never;
            issue_credential_batch?: never;
            revoke_credentials?: never;
            protocol_version_update?: never;
            deactivate_did?: never;
        } | {
            create_did?: never;
            update_did?: UpdateDIDOperation;
            issue_credential_batch?: never;
            revoke_credentials?: never;
            protocol_version_update?: never;
            deactivate_did?: never;
        } | {
            create_did?: never;
            update_did?: never;
            issue_credential_batch?: IssueCredentialBatchOperation;
            revoke_credentials?: never;
            protocol_version_update?: never;
            deactivate_did?: never;
        } | {
            create_did?: never;
            update_did?: never;
            issue_credential_batch?: never;
            revoke_credentials?: RevokeCredentialsOperation;
            protocol_version_update?: never;
            deactivate_did?: never;
        } | {
            create_did?: never;
            update_did?: never;
            issue_credential_batch?: never;
            revoke_credentials?: never;
            protocol_version_update?: ProtocolVersionUpdateOperation;
            deactivate_did?: never;
        } | {
            create_did?: never;
            update_did?: never;
            issue_credential_batch?: never;
            revoke_credentials?: never;
            protocol_version_update?: never;
            deactivate_did?: DeactivateDIDOperation;
        }))));
        get create_did(): CreateDIDOperation;
        set create_did(value: CreateDIDOperation);
        get has_create_did(): boolean;
        get update_did(): UpdateDIDOperation;
        set update_did(value: UpdateDIDOperation);
        get has_update_did(): boolean;
        get issue_credential_batch(): IssueCredentialBatchOperation;
        set issue_credential_batch(value: IssueCredentialBatchOperation);
        get has_issue_credential_batch(): boolean;
        get revoke_credentials(): RevokeCredentialsOperation;
        set revoke_credentials(value: RevokeCredentialsOperation);
        get has_revoke_credentials(): boolean;
        get protocol_version_update(): ProtocolVersionUpdateOperation;
        set protocol_version_update(value: ProtocolVersionUpdateOperation);
        get has_protocol_version_update(): boolean;
        get deactivate_did(): DeactivateDIDOperation;
        set deactivate_did(value: DeactivateDIDOperation);
        get has_deactivate_did(): boolean;
        get operation(): "none" | "create_did" | "update_did" | "issue_credential_batch" | "revoke_credentials" | "protocol_version_update" | "deactivate_did";
        static fromObject(data: {
            create_did?: ReturnType<typeof CreateDIDOperation.prototype.toObject>;
            update_did?: ReturnType<typeof UpdateDIDOperation.prototype.toObject>;
            issue_credential_batch?: ReturnType<typeof IssueCredentialBatchOperation.prototype.toObject>;
            revoke_credentials?: ReturnType<typeof RevokeCredentialsOperation.prototype.toObject>;
            protocol_version_update?: ReturnType<typeof ProtocolVersionUpdateOperation.prototype.toObject>;
            deactivate_did?: ReturnType<typeof DeactivateDIDOperation.prototype.toObject>;
        }): AtalaOperation;
        toObject(): {
            create_did?: {
                did_data?: {
                    public_keys?: {
                        id?: string | undefined;
                        usage?: KeyUsage | undefined;
                        added_on?: {
                            transaction_id?: string | undefined;
                            ledger?: dependency_1.io.iohk.atala.prism.protos.Ledger | undefined;
                            timestamp_info?: {
                                block_sequence_number?: number | undefined;
                                operation_sequence_number?: number | undefined;
                                block_timestamp?: {
                                    seconds?: number | undefined;
                                    nanos?: number | undefined;
                                } | undefined;
                            } | undefined;
                        } | undefined;
                        revoked_on?: {
                            transaction_id?: string | undefined;
                            ledger?: dependency_1.io.iohk.atala.prism.protos.Ledger | undefined;
                            timestamp_info?: {
                                block_sequence_number?: number | undefined;
                                operation_sequence_number?: number | undefined;
                                block_timestamp?: {
                                    seconds?: number | undefined;
                                    nanos?: number | undefined;
                                } | undefined;
                            } | undefined;
                        } | undefined;
                        ec_key_data?: {
                            curve?: string | undefined;
                            x?: Uint8Array | undefined;
                            y?: Uint8Array | undefined;
                        } | undefined;
                        compressed_ec_key_data?: {
                            curve?: string | undefined;
                            data?: Uint8Array | undefined;
                        } | undefined;
                    }[] | undefined;
                    services?: {
                        id?: string | undefined;
                        type?: string | undefined;
                        service_endpoint?: string[] | undefined;
                        added_on?: {
                            transaction_id?: string | undefined;
                            ledger?: dependency_1.io.iohk.atala.prism.protos.Ledger | undefined;
                            timestamp_info?: {
                                block_sequence_number?: number | undefined;
                                operation_sequence_number?: number | undefined;
                                block_timestamp?: {
                                    seconds?: number | undefined;
                                    nanos?: number | undefined;
                                } | undefined;
                            } | undefined;
                        } | undefined;
                        deleted_on?: {
                            transaction_id?: string | undefined;
                            ledger?: dependency_1.io.iohk.atala.prism.protos.Ledger | undefined;
                            timestamp_info?: {
                                block_sequence_number?: number | undefined;
                                operation_sequence_number?: number | undefined;
                                block_timestamp?: {
                                    seconds?: number | undefined;
                                    nanos?: number | undefined;
                                } | undefined;
                            } | undefined;
                        } | undefined;
                    }[] | undefined;
                } | undefined;
            } | undefined;
            update_did?: {
                previous_operation_hash?: Uint8Array | undefined;
                id?: string | undefined;
                actions?: {
                    add_key?: {
                        key?: {
                            id?: string | undefined;
                            usage?: KeyUsage | undefined;
                            added_on?: {
                                transaction_id?: string | undefined;
                                ledger?: dependency_1.io.iohk.atala.prism.protos.Ledger | undefined;
                                timestamp_info?: {
                                    block_sequence_number?: number | undefined;
                                    operation_sequence_number?: number | undefined;
                                    block_timestamp?: {
                                        seconds?: number | undefined;
                                        nanos?: number | undefined;
                                    } | undefined;
                                } | undefined;
                            } | undefined;
                            revoked_on?: {
                                transaction_id?: string | undefined;
                                ledger?: dependency_1.io.iohk.atala.prism.protos.Ledger | undefined;
                                timestamp_info?: {
                                    block_sequence_number?: number | undefined;
                                    operation_sequence_number?: number | undefined;
                                    block_timestamp?: {
                                        seconds?: number | undefined;
                                        nanos?: number | undefined;
                                    } | undefined;
                                } | undefined;
                            } | undefined;
                            ec_key_data?: {
                                curve?: string | undefined;
                                x?: Uint8Array | undefined;
                                y?: Uint8Array | undefined;
                            } | undefined;
                            compressed_ec_key_data?: {
                                curve?: string | undefined;
                                data?: Uint8Array | undefined;
                            } | undefined;
                        } | undefined;
                    } | undefined;
                    remove_key?: {
                        keyId?: string | undefined;
                    } | undefined;
                    add_service?: {
                        service?: {
                            id?: string | undefined;
                            type?: string | undefined;
                            service_endpoint?: string[] | undefined;
                            added_on?: {
                                transaction_id?: string | undefined;
                                ledger?: dependency_1.io.iohk.atala.prism.protos.Ledger | undefined;
                                timestamp_info?: {
                                    block_sequence_number?: number | undefined;
                                    operation_sequence_number?: number | undefined;
                                    block_timestamp?: {
                                        seconds?: number | undefined;
                                        nanos?: number | undefined;
                                    } | undefined;
                                } | undefined;
                            } | undefined;
                            deleted_on?: {
                                transaction_id?: string | undefined;
                                ledger?: dependency_1.io.iohk.atala.prism.protos.Ledger | undefined;
                                timestamp_info?: {
                                    block_sequence_number?: number | undefined;
                                    operation_sequence_number?: number | undefined;
                                    block_timestamp?: {
                                        seconds?: number | undefined;
                                        nanos?: number | undefined;
                                    } | undefined;
                                } | undefined;
                            } | undefined;
                        } | undefined;
                    } | undefined;
                    remove_service?: {
                        serviceId?: string | undefined;
                    } | undefined;
                    update_service?: {
                        serviceId?: string | undefined;
                        type?: string | undefined;
                        service_endpoints?: string[] | undefined;
                    } | undefined;
                }[] | undefined;
            } | undefined;
            issue_credential_batch?: {
                credential_batch_data?: {
                    issuer_did?: string | undefined;
                    merkle_root?: Uint8Array | undefined;
                } | undefined;
            } | undefined;
            revoke_credentials?: {
                previous_operation_hash?: Uint8Array | undefined;
                credential_batch_id?: string | undefined;
                credentials_to_revoke?: Uint8Array[] | undefined;
            } | undefined;
            protocol_version_update?: {
                proposer_did?: string | undefined;
                version?: {
                    version_name?: string | undefined;
                    effective_since?: number | undefined;
                    protocol_version?: {
                        major_version?: number | undefined;
                        minor_version?: number | undefined;
                    } | undefined;
                } | undefined;
            } | undefined;
            deactivate_did?: {
                previous_operation_hash?: Uint8Array | undefined;
                id?: string | undefined;
            } | undefined;
        };
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): AtalaOperation;
        serializeBinary(): Uint8Array;
        static deserializeBinary(bytes: Uint8Array): AtalaOperation;
    }
    class SignedAtalaOperation extends pb_1.Message {
        #private;
        constructor(data?: any[] | {
            signed_with?: string;
            signature?: Uint8Array;
            operation?: AtalaOperation;
        });
        get signed_with(): string;
        set signed_with(value: string);
        get signature(): Uint8Array;
        set signature(value: Uint8Array);
        get operation(): AtalaOperation;
        set operation(value: AtalaOperation);
        get has_operation(): boolean;
        static fromObject(data: {
            signed_with?: string;
            signature?: Uint8Array;
            operation?: ReturnType<typeof AtalaOperation.prototype.toObject>;
        }): SignedAtalaOperation;
        toObject(): {
            signed_with?: string | undefined;
            signature?: Uint8Array | undefined;
            operation?: {
                create_did?: {
                    did_data?: {
                        public_keys?: {
                            id?: string | undefined;
                            usage?: KeyUsage | undefined;
                            added_on?: {
                                transaction_id?: string | undefined;
                                ledger?: dependency_1.io.iohk.atala.prism.protos.Ledger | undefined;
                                timestamp_info?: {
                                    block_sequence_number?: number | undefined;
                                    operation_sequence_number?: number | undefined;
                                    block_timestamp?: {
                                        seconds?: number | undefined;
                                        nanos?: number | undefined;
                                    } | undefined;
                                } | undefined;
                            } | undefined;
                            revoked_on?: {
                                transaction_id?: string | undefined;
                                ledger?: dependency_1.io.iohk.atala.prism.protos.Ledger | undefined;
                                timestamp_info?: {
                                    block_sequence_number?: number | undefined;
                                    operation_sequence_number?: number | undefined;
                                    block_timestamp?: {
                                        seconds?: number | undefined;
                                        nanos?: number | undefined;
                                    } | undefined;
                                } | undefined;
                            } | undefined;
                            ec_key_data?: {
                                curve?: string | undefined;
                                x?: Uint8Array | undefined;
                                y?: Uint8Array | undefined;
                            } | undefined;
                            compressed_ec_key_data?: {
                                curve?: string | undefined;
                                data?: Uint8Array | undefined;
                            } | undefined;
                        }[] | undefined;
                        services?: {
                            id?: string | undefined;
                            type?: string | undefined;
                            service_endpoint?: string[] | undefined;
                            added_on?: {
                                transaction_id?: string | undefined;
                                ledger?: dependency_1.io.iohk.atala.prism.protos.Ledger | undefined;
                                timestamp_info?: {
                                    block_sequence_number?: number | undefined;
                                    operation_sequence_number?: number | undefined;
                                    block_timestamp?: {
                                        seconds?: number | undefined;
                                        nanos?: number | undefined;
                                    } | undefined;
                                } | undefined;
                            } | undefined;
                            deleted_on?: {
                                transaction_id?: string | undefined;
                                ledger?: dependency_1.io.iohk.atala.prism.protos.Ledger | undefined;
                                timestamp_info?: {
                                    block_sequence_number?: number | undefined;
                                    operation_sequence_number?: number | undefined;
                                    block_timestamp?: {
                                        seconds?: number | undefined;
                                        nanos?: number | undefined;
                                    } | undefined;
                                } | undefined;
                            } | undefined;
                        }[] | undefined;
                    } | undefined;
                } | undefined;
                update_did?: {
                    previous_operation_hash?: Uint8Array | undefined;
                    id?: string | undefined;
                    actions?: {
                        add_key?: {
                            key?: {
                                id?: string | undefined;
                                usage?: KeyUsage | undefined;
                                added_on?: {
                                    transaction_id?: string | undefined;
                                    ledger?: dependency_1.io.iohk.atala.prism.protos.Ledger | undefined;
                                    timestamp_info?: {
                                        block_sequence_number?: number | undefined;
                                        operation_sequence_number?: number | undefined;
                                        block_timestamp?: {
                                            seconds?: number | undefined;
                                            nanos?: number | undefined;
                                        } | undefined;
                                    } | undefined;
                                } | undefined;
                                revoked_on?: {
                                    transaction_id?: string | undefined;
                                    ledger?: dependency_1.io.iohk.atala.prism.protos.Ledger | undefined;
                                    timestamp_info?: {
                                        block_sequence_number?: number | undefined;
                                        operation_sequence_number?: number | undefined;
                                        block_timestamp?: {
                                            seconds?: number | undefined;
                                            nanos?: number | undefined;
                                        } | undefined;
                                    } | undefined;
                                } | undefined;
                                ec_key_data?: {
                                    curve?: string | undefined;
                                    x?: Uint8Array | undefined;
                                    y?: Uint8Array | undefined;
                                } | undefined;
                                compressed_ec_key_data?: {
                                    curve?: string | undefined;
                                    data?: Uint8Array | undefined;
                                } | undefined;
                            } | undefined;
                        } | undefined;
                        remove_key?: {
                            keyId?: string | undefined;
                        } | undefined;
                        add_service?: {
                            service?: {
                                id?: string | undefined;
                                type?: string | undefined;
                                service_endpoint?: string[] | undefined;
                                added_on?: {
                                    transaction_id?: string | undefined;
                                    ledger?: dependency_1.io.iohk.atala.prism.protos.Ledger | undefined;
                                    timestamp_info?: {
                                        block_sequence_number?: number | undefined;
                                        operation_sequence_number?: number | undefined;
                                        block_timestamp?: {
                                            seconds?: number | undefined;
                                            nanos?: number | undefined;
                                        } | undefined;
                                    } | undefined;
                                } | undefined;
                                deleted_on?: {
                                    transaction_id?: string | undefined;
                                    ledger?: dependency_1.io.iohk.atala.prism.protos.Ledger | undefined;
                                    timestamp_info?: {
                                        block_sequence_number?: number | undefined;
                                        operation_sequence_number?: number | undefined;
                                        block_timestamp?: {
                                            seconds?: number | undefined;
                                            nanos?: number | undefined;
                                        } | undefined;
                                    } | undefined;
                                } | undefined;
                            } | undefined;
                        } | undefined;
                        remove_service?: {
                            serviceId?: string | undefined;
                        } | undefined;
                        update_service?: {
                            serviceId?: string | undefined;
                            type?: string | undefined;
                            service_endpoints?: string[] | undefined;
                        } | undefined;
                    }[] | undefined;
                } | undefined;
                issue_credential_batch?: {
                    credential_batch_data?: {
                        issuer_did?: string | undefined;
                        merkle_root?: Uint8Array | undefined;
                    } | undefined;
                } | undefined;
                revoke_credentials?: {
                    previous_operation_hash?: Uint8Array | undefined;
                    credential_batch_id?: string | undefined;
                    credentials_to_revoke?: Uint8Array[] | undefined;
                } | undefined;
                protocol_version_update?: {
                    proposer_did?: string | undefined;
                    version?: {
                        version_name?: string | undefined;
                        effective_since?: number | undefined;
                        protocol_version?: {
                            major_version?: number | undefined;
                            minor_version?: number | undefined;
                        } | undefined;
                    } | undefined;
                } | undefined;
                deactivate_did?: {
                    previous_operation_hash?: Uint8Array | undefined;
                    id?: string | undefined;
                } | undefined;
            } | undefined;
        };
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): SignedAtalaOperation;
        serializeBinary(): Uint8Array;
        static deserializeBinary(bytes: Uint8Array): SignedAtalaOperation;
    }
    class LedgerData extends pb_1.Message {
        #private;
        constructor(data?: any[] | {
            transaction_id?: string;
            ledger?: dependency_1.io.iohk.atala.prism.protos.Ledger;
            timestamp_info?: TimestampInfo;
        });
        get transaction_id(): string;
        set transaction_id(value: string);
        get ledger(): dependency_1.io.iohk.atala.prism.protos.Ledger;
        set ledger(value: dependency_1.io.iohk.atala.prism.protos.Ledger);
        get timestamp_info(): TimestampInfo;
        set timestamp_info(value: TimestampInfo);
        get has_timestamp_info(): boolean;
        static fromObject(data: {
            transaction_id?: string;
            ledger?: dependency_1.io.iohk.atala.prism.protos.Ledger;
            timestamp_info?: ReturnType<typeof TimestampInfo.prototype.toObject>;
        }): LedgerData;
        toObject(): {
            transaction_id?: string | undefined;
            ledger?: dependency_1.io.iohk.atala.prism.protos.Ledger | undefined;
            timestamp_info?: {
                block_sequence_number?: number | undefined;
                operation_sequence_number?: number | undefined;
                block_timestamp?: {
                    seconds?: number | undefined;
                    nanos?: number | undefined;
                } | undefined;
            } | undefined;
        };
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): LedgerData;
        serializeBinary(): Uint8Array;
        static deserializeBinary(bytes: Uint8Array): LedgerData;
    }
    class OperationOutput extends pb_1.Message {
        #private;
        constructor(data?: any[] | ({} & (({
            batch_output?: IssueCredentialBatchOutput;
            create_did_output?: never;
            update_did_output?: never;
            revoke_credentials_output?: never;
            protocol_version_update_output?: never;
            deactivate_did_output?: never;
        } | {
            batch_output?: never;
            create_did_output?: CreateDIDOutput;
            update_did_output?: never;
            revoke_credentials_output?: never;
            protocol_version_update_output?: never;
            deactivate_did_output?: never;
        } | {
            batch_output?: never;
            create_did_output?: never;
            update_did_output?: UpdateDIDOutput;
            revoke_credentials_output?: never;
            protocol_version_update_output?: never;
            deactivate_did_output?: never;
        } | {
            batch_output?: never;
            create_did_output?: never;
            update_did_output?: never;
            revoke_credentials_output?: RevokeCredentialsOutput;
            protocol_version_update_output?: never;
            deactivate_did_output?: never;
        } | {
            batch_output?: never;
            create_did_output?: never;
            update_did_output?: never;
            revoke_credentials_output?: never;
            protocol_version_update_output?: ProtocolVersionUpdateOutput;
            deactivate_did_output?: never;
        } | {
            batch_output?: never;
            create_did_output?: never;
            update_did_output?: never;
            revoke_credentials_output?: never;
            protocol_version_update_output?: never;
            deactivate_did_output?: DeactivateDIDOutput;
        }) | ({
            operation_id?: Uint8Array;
            error?: never;
        } | {
            operation_id?: never;
            error?: string;
        }))));
        get batch_output(): IssueCredentialBatchOutput;
        set batch_output(value: IssueCredentialBatchOutput);
        get has_batch_output(): boolean;
        get create_did_output(): CreateDIDOutput;
        set create_did_output(value: CreateDIDOutput);
        get has_create_did_output(): boolean;
        get update_did_output(): UpdateDIDOutput;
        set update_did_output(value: UpdateDIDOutput);
        get has_update_did_output(): boolean;
        get revoke_credentials_output(): RevokeCredentialsOutput;
        set revoke_credentials_output(value: RevokeCredentialsOutput);
        get has_revoke_credentials_output(): boolean;
        get protocol_version_update_output(): ProtocolVersionUpdateOutput;
        set protocol_version_update_output(value: ProtocolVersionUpdateOutput);
        get has_protocol_version_update_output(): boolean;
        get deactivate_did_output(): DeactivateDIDOutput;
        set deactivate_did_output(value: DeactivateDIDOutput);
        get has_deactivate_did_output(): boolean;
        get operation_id(): Uint8Array;
        set operation_id(value: Uint8Array);
        get has_operation_id(): boolean;
        get error(): string;
        set error(value: string);
        get has_error(): boolean;
        get result(): "none" | "batch_output" | "create_did_output" | "update_did_output" | "revoke_credentials_output" | "protocol_version_update_output" | "deactivate_did_output";
        get operation_maybe(): "none" | "error" | "operation_id";
        static fromObject(data: {
            batch_output?: ReturnType<typeof IssueCredentialBatchOutput.prototype.toObject>;
            create_did_output?: ReturnType<typeof CreateDIDOutput.prototype.toObject>;
            update_did_output?: ReturnType<typeof UpdateDIDOutput.prototype.toObject>;
            revoke_credentials_output?: ReturnType<typeof RevokeCredentialsOutput.prototype.toObject>;
            protocol_version_update_output?: ReturnType<typeof ProtocolVersionUpdateOutput.prototype.toObject>;
            deactivate_did_output?: ReturnType<typeof DeactivateDIDOutput.prototype.toObject>;
            operation_id?: Uint8Array;
            error?: string;
        }): OperationOutput;
        toObject(): {
            batch_output?: {
                batch_id?: string | undefined;
            } | undefined;
            create_did_output?: {
                did_suffix?: string | undefined;
            } | undefined;
            update_did_output?: {} | undefined;
            revoke_credentials_output?: {} | undefined;
            protocol_version_update_output?: {} | undefined;
            deactivate_did_output?: {} | undefined;
            operation_id?: Uint8Array | undefined;
            error?: string | undefined;
        };
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): OperationOutput;
        serializeBinary(): Uint8Array;
        static deserializeBinary(bytes: Uint8Array): OperationOutput;
    }
    class IssueCredentialBatchOutput extends pb_1.Message {
        #private;
        constructor(data?: any[] | {
            batch_id?: string;
        });
        get batch_id(): string;
        set batch_id(value: string);
        static fromObject(data: {
            batch_id?: string;
        }): IssueCredentialBatchOutput;
        toObject(): {
            batch_id?: string | undefined;
        };
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): IssueCredentialBatchOutput;
        serializeBinary(): Uint8Array;
        static deserializeBinary(bytes: Uint8Array): IssueCredentialBatchOutput;
    }
    class CreateDIDOutput extends pb_1.Message {
        #private;
        constructor(data?: any[] | {
            did_suffix?: string;
        });
        get did_suffix(): string;
        set did_suffix(value: string);
        static fromObject(data: {
            did_suffix?: string;
        }): CreateDIDOutput;
        toObject(): {
            did_suffix?: string | undefined;
        };
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): CreateDIDOutput;
        serializeBinary(): Uint8Array;
        static deserializeBinary(bytes: Uint8Array): CreateDIDOutput;
    }
    class UpdateDIDOutput extends pb_1.Message {
        #private;
        constructor(data?: any[] | {});
        static fromObject(data: {}): UpdateDIDOutput;
        toObject(): {};
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): UpdateDIDOutput;
        serializeBinary(): Uint8Array;
        static deserializeBinary(bytes: Uint8Array): UpdateDIDOutput;
    }
    class RevokeCredentialsOutput extends pb_1.Message {
        #private;
        constructor(data?: any[] | {});
        static fromObject(data: {}): RevokeCredentialsOutput;
        toObject(): {};
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): RevokeCredentialsOutput;
        serializeBinary(): Uint8Array;
        static deserializeBinary(bytes: Uint8Array): RevokeCredentialsOutput;
    }
    class ProtocolVersionUpdateOutput extends pb_1.Message {
        #private;
        constructor(data?: any[] | {});
        static fromObject(data: {}): ProtocolVersionUpdateOutput;
        toObject(): {};
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): ProtocolVersionUpdateOutput;
        serializeBinary(): Uint8Array;
        static deserializeBinary(bytes: Uint8Array): ProtocolVersionUpdateOutput;
    }
    class DeactivateDIDOutput extends pb_1.Message {
        #private;
        constructor(data?: any[] | {});
        static fromObject(data: {}): DeactivateDIDOutput;
        toObject(): {};
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): DeactivateDIDOutput;
        serializeBinary(): Uint8Array;
        static deserializeBinary(bytes: Uint8Array): DeactivateDIDOutput;
    }
    class Service extends pb_1.Message {
        #private;
        constructor(data?: any[] | {
            id?: string;
            type?: string;
            service_endpoint?: string[];
            added_on?: LedgerData;
            deleted_on?: LedgerData;
        });
        get id(): string;
        set id(value: string);
        get type(): string;
        set type(value: string);
        get service_endpoint(): string[];
        set service_endpoint(value: string[]);
        get added_on(): LedgerData;
        set added_on(value: LedgerData);
        get has_added_on(): boolean;
        get deleted_on(): LedgerData;
        set deleted_on(value: LedgerData);
        get has_deleted_on(): boolean;
        static fromObject(data: {
            id?: string;
            type?: string;
            service_endpoint?: string[];
            added_on?: ReturnType<typeof LedgerData.prototype.toObject>;
            deleted_on?: ReturnType<typeof LedgerData.prototype.toObject>;
        }): Service;
        toObject(): {
            id?: string | undefined;
            type?: string | undefined;
            service_endpoint?: string[] | undefined;
            added_on?: {
                transaction_id?: string | undefined;
                ledger?: dependency_1.io.iohk.atala.prism.protos.Ledger | undefined;
                timestamp_info?: {
                    block_sequence_number?: number | undefined;
                    operation_sequence_number?: number | undefined;
                    block_timestamp?: {
                        seconds?: number | undefined;
                        nanos?: number | undefined;
                    } | undefined;
                } | undefined;
            } | undefined;
            deleted_on?: {
                transaction_id?: string | undefined;
                ledger?: dependency_1.io.iohk.atala.prism.protos.Ledger | undefined;
                timestamp_info?: {
                    block_sequence_number?: number | undefined;
                    operation_sequence_number?: number | undefined;
                    block_timestamp?: {
                        seconds?: number | undefined;
                        nanos?: number | undefined;
                    } | undefined;
                } | undefined;
            } | undefined;
        };
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): Service;
        serializeBinary(): Uint8Array;
        static deserializeBinary(bytes: Uint8Array): Service;
    }
}
