import { ATN } from "antlr4ts/atn/ATN";
import { CharStream } from "antlr4ts/CharStream";
import { Lexer } from "antlr4ts/Lexer";
import { Vocabulary } from "antlr4ts/Vocabulary";
export declare class DIDUrlAbnfLexer extends Lexer {
    static readonly T__0 = 1;
    static readonly T__1 = 2;
    static readonly T__2 = 3;
    static readonly T__3 = 4;
    static readonly SCHEMA = 5;
    static readonly ALPHA = 6;
    static readonly DIGIT = 7;
    static readonly PCT_ENCODED = 8;
    static readonly PERCENT = 9;
    static readonly DASH = 10;
    static readonly PERIOD = 11;
    static readonly COLON = 12;
    static readonly UNDERSCORE = 13;
    static readonly HEX = 14;
    static readonly STRING = 15;
    static readonly SLASH = 16;
    static readonly channelNames: string[];
    static readonly modeNames: string[];
    static readonly ruleNames: string[];
    private static readonly _LITERAL_NAMES;
    private static readonly _SYMBOLIC_NAMES;
    static readonly VOCABULARY: Vocabulary;
    get vocabulary(): Vocabulary;
    constructor(input: CharStream);
    get grammarFileName(): string;
    get ruleNames(): string[];
    get serializedATN(): string;
    get channelNames(): string[];
    get modeNames(): string[];
    static readonly _serializedATN: string;
    static __ATN: ATN;
    static get _ATN(): ATN;
}
